"""add last_generated_date to recurring_transactions

Revision ID: 9aec0a4c7332
Revises: a6fa4e94ddb0
Create Date: 2026-08-10 11:31:45.792957

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9aec0a4c7332"
down_revision: Union[str, Sequence[str], None] = "a6fa4e94ddb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recurring_transactions", sa.Column("last_generated_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recurring_transactions", "last_generated_date")
    # ### end Alembic commands ###
