"""initial schema

Revision ID: bfca510ab01f
Revises:
Create Date: 2026-08-10 08:24:20.586037

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfca510ab01f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "type", sa.Enum("bank", "cash", "credit_card", name="asset_type"), nullable=False
        ),
        sa.Column("balance", sa.DECIMAL(precision=12, scale=0), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "income_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "major_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "expense_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("major_category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["major_category_id"],
            ["major_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("major_category_id", "name", name="uq_expense_category_major_name"),
    )
    op.create_table(
        "recurring_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=12, scale=0), nullable=False),
        sa.Column("entry_kind", sa.Enum("income", "expense", name="entry_kind"), nullable=False),
        sa.Column("major_category_id", sa.Integer(), nullable=True),
        sa.Column("expense_category_id", sa.Integer(), nullable=True),
        sa.Column("income_category_id", sa.Integer(), nullable=True),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("memo", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_category_id"],
            ["expense_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["income_category_id"],
            ["income_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["major_category_id"],
            ["major_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=12, scale=0), nullable=False),
        sa.Column("entry_kind", sa.Enum("income", "expense", name="entry_kind"), nullable=False),
        sa.Column("entry_type", sa.Enum("normal", "adjustment", name="entry_type"), nullable=False),
        sa.Column("major_category_id", sa.Integer(), nullable=True),
        sa.Column("expense_category_id", sa.Integer(), nullable=True),
        sa.Column("income_category_id", sa.Integer(), nullable=True),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("memo", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expense_category_id"],
            ["expense_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["income_category_id"],
            ["income_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["major_category_id"],
            ["major_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transactions_date", "transactions", ["date"], unique=False)
    # ### end Alembic commands ###

    _seed_categories()


def _seed_categories() -> None:
    major_categories = sa.table(
        "major_categories",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("sort_order", sa.Integer),
    )
    expense_categories = sa.table(
        "expense_categories",
        sa.column("major_category_id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("sort_order", sa.Integer),
    )
    income_categories = sa.table(
        "income_categories",
        sa.column("name", sa.String),
        sa.column("sort_order", sa.Integer),
    )

    op.bulk_insert(
        major_categories,
        [
            {"id": 1, "name": "固定費", "sort_order": 1},
            {"id": 2, "name": "食費", "sort_order": 2},
            {"id": 3, "name": "生活費", "sort_order": 3},
            {"id": 4, "name": "娯楽費", "sort_order": 4},
        ],
    )
    op.bulk_insert(
        expense_categories,
        [
            {"major_category_id": 1, "name": "水道光熱費", "sort_order": 1},
            {"major_category_id": 1, "name": "家賃", "sort_order": 2},
            {"major_category_id": 1, "name": "通信費", "sort_order": 3},
            {"major_category_id": 2, "name": "食材", "sort_order": 1},
            {"major_category_id": 2, "name": "外食", "sort_order": 2},
            {"major_category_id": 3, "name": "日用品", "sort_order": 1},
            {"major_category_id": 3, "name": "医療費", "sort_order": 2},
            {"major_category_id": 4, "name": "趣味", "sort_order": 1},
            {"major_category_id": 4, "name": "旅行", "sort_order": 2},
        ],
    )
    op.bulk_insert(
        income_categories,
        [
            {"name": "給与", "sort_order": 1},
            {"name": "賞与", "sort_order": 2},
            {"name": "副収入", "sort_order": 3},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_date", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("recurring_transactions")
    op.drop_table("expense_categories")
    op.drop_table("major_categories")
    op.drop_table("income_categories")
    op.drop_table("assets")
    # ### end Alembic commands ###
